build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    
    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "llvm/3.9.0"
    CONAN_USERNAME: "russelltg"
    CONAN_CHANNEL: "stable"
    CONAN_TOTAL_PAGES: 32
    CONAN_VISUAL_VERSIONS: 12,14
    CONAN_PASSWORD:
        secure: pQ38xT4+8uWvKYmblQYWyQ==
    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4
        - CONAN_CURRENT_PAGE: 5
        - CONAN_CURRENT_PAGE: 6
        - CONAN_CURRENT_PAGE: 7
        - CONAN_CURRENT_PAGE: 8
        - CONAN_CURRENT_PAGE: 9
        - CONAN_CURRENT_PAGE: 10
        - CONAN_CURRENT_PAGE: 11
        - CONAN_CURRENT_PAGE: 12
        - CONAN_CURRENT_PAGE: 13
        - CONAN_CURRENT_PAGE: 14
        - CONAN_CURRENT_PAGE: 15
        - CONAN_CURRENT_PAGE: 16
        - CONAN_CURRENT_PAGE: 17
        - CONAN_CURRENT_PAGE: 18
        - CONAN_CURRENT_PAGE: 19
        - CONAN_CURRENT_PAGE: 20
        - CONAN_CURRENT_PAGE: 21
        - CONAN_CURRENT_PAGE: 22
        - CONAN_CURRENT_PAGE: 23
        - CONAN_CURRENT_PAGE: 24
        - CONAN_CURRENT_PAGE: 25
        - CONAN_CURRENT_PAGE: 26
        - CONAN_CURRENT_PAGE: 27
        - CONAN_CURRENT_PAGE: 28
        - CONAN_CURRENT_PAGE: 29
        - CONAN_CURRENT_PAGE: 30
        - CONAN_CURRENT_PAGE: 31
        - CONAN_CURRENT_PAGE: 32
    
    
install:
    - set PATH=%PATH%;%PYTHON%/Scripts/
    - pip.exe install conan_package_tools
    - conan user
    
test_script:
    - python run.py
    
